services:
  # Servicio 1: Plataforma Web Streamlit
  communitylab-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: communitylab_web
    ports:
      - "8510:8501"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./run_app.py:/app/run_app.py
      - ./data:/app/data
    restart: unless-stopped

  # Servicio 2: Bot de Ingesta Discord en Tiempo Real (Escucha y escribe en data/raw)
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: communitylab_bot
    command: ["python", "-m", "src.adapters.ingestion.discord_bot"]
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    restart: unless-stopped